### ISSUE TITLE
Aderyn not working correctly.

### ISSUE THREAD

**Issue by exolorkistis** [Cyfrin/aderyn#153]
I am using VSCode and i am using Gitbash terminal.So i installed aderyn according to the repository guidance and while it runs without errors when i give the aderyn . command and the report.md is created the report never finds any results even in the projects of the course.

Below is the text i get when running the command:
```

$ aderyn .
Detecting framework...
Framework detected: Foundry mode engaged.
Foundry root path: "."
[⠒] Compiling...
[⠆] Compiling 41 files with 0.8.20
[⠔] Solc 0.8.20 finished in 15.36s
Compiler run successful!
Foundry src path: ".\\src"
Get Detectors
Running 18 detectors
Detectors run, processing found issues 
Found issues processed. Printing report
Report printed to report.md
```
A report.md is created but everytime it looks like this with no results:

# Aderyn Analysis Report

This report was generated by [Aderyn](https://github.com/Cyfrin/aderyn), a static analysis tool built by [Cyfrin](https://cyfrin.io), a blockchain security company. This report is not a substitute for manual audit or security review. It should not be relied upon for any purpose other than to assist in the identification of potential security vulnerabilities.
# Table of Contents

- [Summary](#summary)
  - [Files Summary](#files-summary)
  - [Files Details](#files-details)
  - [Issue Summary](#issue-summary)

# Summary

## Files Summary

| Key | Value |
| --- | --- |
| .sol Files | 0 |
| Total nSLOC | 0 |

## Files Details

| Filepath | nSLOC |
| --- | --- |
| **Total** | **0** |

## Issue Summary

| Category | No. of Issues |
| --- | --- |
| Critical | 0 |
| High | 0 |
| Medium | 0 |
| Low | 0 |
| NC | 0 |

I get the same results in avery project i have tried using it.No change.How can i make it work?Is there something else i should have installed that it is not mentioned in the repository?

**Comment by TilakMaddy** [comment]
@alexroan I'm guessing that this line

[https://github.com/Cyfrin/aderyn/blame/9eec7d53587bc4aa24809cbe8bffc0b491298e65/aderyn_core/src/framework/foundry.rs#L165](https://github.com/Cyfrin/aderyn/blame/9eec7d53587bc4aa24809cbe8bffc0b491298e65/aderyn_core/src/framework/foundry.rs#L165)

only caters to *nix systems because Windows doesn't use `/` in its file paths.

Do you see any downsides to make the following change?

```diff
- if subdir_str.contains(&format!("/{}", contract_name)) {
+ if subdir_str.ends_with(&format!("{}", contract_name)) {
```

`cli/reportgen.sh` seems to not create any different result : ) Although later we can look into component-ifying paths : )

**Comment by TilakMaddy** [comment]
@exolorkistis Thank you for bringing this up. Forge can do its thing according to what you have shown. So no, you need not install any extra stuff! I am guessing this is an internal issue. I remember seeing this exact problem faced by some other user in the security-course discussion forum however this confirms it : )

**Comment by TilakMaddy** [comment]
PR - https://github.com/Cyfrin/aderyn/pull/154

**Comment by exolorkistis** [comment]
no. i have tried but i get the same result.

**Comment by alexroan** [comment]
Can you paste your `foundry.toml` contents here please @exolorkistis .

This looks strange: `Foundry src path: ".\\src"`

**Comment by TilakMaddy** [comment]
Could you also take a quick look inside `out` folder and make sure it's not empty?

**Comment by exolorkistis** [comment]
no its not empty it has smart contracts inside.

**Comment by exolorkistis** [comment]
> Can you paste your `foundry.toml` contents here please @exolorkistis .
> 
> This looks strange: `Foundry src path: ".\\src"`


Sure here it is:

[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts',
    '@openzeppelin/contracts-upgradeable=lib/openzeppelin-contracts-upgradeable/contracts',
]
solc = '0.8.20'

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

**Comment by exolorkistis** [comment]
aris@DESKTOP-07RERAM MINGW64 ~/Security-Course/6-thunder-loan-audit (main)
$ pwd
/c/Users/aris/Security-Course/6-thunder-loan-audit

**Comment by TilakMaddy** [comment]
@alexroan I think that the weird thing ".\\src" is because when we shell out the command forge build, it happens in a native windows shell. However it's executed in gitbash env which is still windows. Had it been WSL, this would not have been the case.

**Comment by alexroan** [comment]
Stale
