### ISSUE TITLE
Any reason we don't propagate accept for override specifiers in modifiers?

### ISSUE THREAD

**Issue by TilakMaddy** [Cyfrin/aderyn#184]
[here in these lines](https://github.com/Cyfrin/aderyn/blob/34dc997e75e593b6cf2e997cdf7eeff323780944/aderyn_core/src/ast/modifiers.rs#L24C9-L29C10) , we don't propagate the accept on `self.overrides` like we do for `self.body` and `self.parameters`.  

Is this by design ? or by mistake ?

**Comment by TilakMaddy** [comment]
Okay, it's confirmed it is by mistake. 

Source - https://github.com/foundry-rs/compilers/blob/342f713da41c9738c6e775b7daf0bf6827041cde/src/artifacts/ast/visitor.rs#L286

**Comment by alexroan** [comment]
We can add it for sure, we don't have any detectors that use it rn but we might in future.
