### ISSUE TITLE
(Need help) AST parser fails due to missing "ast" field

### ISSUE THREAD

**Issue by TilakMaddy** [Cyfrin/aderyn#191]
Step 1. Nuke the `~/.svm` folder (where foundry installs solc)
Step 2. foundryup
Step 3. forge build 

Then AST parser fails

Sample of the output of `cli/reportgen.sh`
```bash
Error reading Foundry output file: /Users/tilakmadichetti/Documents/OpenSource/realaderyn/tests/contract-playground/out/DepositContract.sol/ERC165.json: missing field `ast` at line 1 column 3887
Error reading Foundry output file: /Users/tilakmadichetti/Documents/OpenSource/realaderyn/tests/contract-playground/out/IContractInheritance.sol/IContractInheritance.0.8.20.json: missing field `ast` at line 1 column 2921
Error reading Foundry output file: /Users/tilakmadichetti/Documents/OpenSource/realaderyn/tests/contract-playground/out/KeccakContract.sol/KeccakContract.json: missing field `ast` at line 1 column 15512
Error reading Foundry output file: /Users/tilakmadichetti/Documents/OpenSource/realaderyn/tests/contract-playground/out/DepositContract.sol/IDepositContract.json: missing field `ast` at line 1 column 7661
Error reading Foundry output file: /Users/tilakmadichetti/Documents/OpenSource/realaderyn/tests/contract-playground/out/Counter.sol/Counter.json: missing field `ast` at line 1 column 7588
Error reading Foundry output file: /Users/tilakmadichetti/Documents/OpenSource/realaderyn/tests/contract-playground/out/2/Nested.sol/Nested.json: missing field `ast` at line 1 column 4285
Error reading Foundry output file: /Users/tilakmadichetti/Documents/OpenSource/realaderyn/tests/contract-playground/out/Counter.sol/Counter.0.8.20.json: missing field `ast` at line 1 column 7588
Error reading Foundry output file: /Users/tilakmadichetti/Documents/OpenSource/realaderyn/tests/contract-playground/out/UniswapV2Swapper.sol/UniswapV2Swapper.json: missing field `ast` at line 1 column 27405
Error reading Foundry output file: /Users/tilakmadichetti/Documents/OpenSource/realaderyn/tests/contract-playground/out/UnsafeERC721Mint.sol/UnsafeERC721Mint.json: missing field `ast` at line 1 column 60363
```

Any help is greatly appreciated : ) 

I am concerned that for nyth projects, in the testing section we pass the path to json file. Can this be something we can avoid ?

**Comment by TilakMaddy** [comment]
@alexroan It appears to me that the new format of json files output by solc doesn't contain ast node

example : 

```bash
Error reading Foundry output file: /XXX/tests/contract-playground/out/Counter.sol/Counter.json: missing field `ast` at line 1 column 7588
Error reading Foundry output file: /XXX/tests/contract-playground/out/2/Nested.sol/Nested.json: missing field `ast` at line 1 column 4285
```


I am finding it difficult to reproduce json output

**Comment by alexroan** [comment]
Ah this could have been caused by this: https://github.com/Cyfrin/aderyn/pull/183

Some AST Nodes don't actually have an ID field @TilakMaddy . This error may be occurring during the parent->child link construction where IDs are crucial.

**Comment by alexroan** [comment]
https://github.com/foundry-rs/foundry/pull/7197 <- Here's the culprit

I've added this PR to fix this issue: #192

**Comment by gakonst** [comment]
Sorry about that folks - we should have notified users!

**Comment by TilakMaddy** [comment]
Helloi @gakonst ! It's okay ... It's been now : ) 

I have a small question for you. Would greatly appreciate any thoughts.


So right now, we're shelling out `forge build --ast` to generate the out folder with all the contracts' jsons.

I was wondering if it's possible that we can use forge codebase as a rust dependency somehow in the Cargo.toml file and make this operation happen ...

What do you think ? Good idea / bad idea / doesn't matter....haha which one is it.:P ??

**Comment by alexroan** [comment]
I like where your head is at. Perhaps open an issue/PR in the foundry codebase @TilakMaddy ?
