### ISSUE TITLE
Detector: variable assigned to ternary operator output not used

### ISSUE THREAD

**Issue by giovannidisiena** [Cyfrin/aderyn#2]
We should add a detector for the following case:

```solidity
function foo(uint256 amount) external returns(uint256 cappedAmount) {
    cappedAmount = amount > s_maxAmount ? s_maxAmount : amount;
    transfer(amount); // `cappedAmount` should be passed here, but instead remains unused
}
```

Here, the variable assigned to the output of the ternary operator is unused because the `amount` input parameter is erroneously passed to the subsequent function call instead of `cappedAmount`, meaning that the value is not capped as intended.

We should add a detector to alert of this case, when the assigned variable remains unused as it could be indicative of this issue.

**Comment by alexroan** [comment]
This already prints a compiler warning, no?

**Comment by giovannidisiena** [comment]
It does, for the unused local variable, but this is specifically for unused local variables declared and assigned the evaluation of ternary operators.

**Comment by TilakMaddy** [comment]
Hmmm this seems to be more of a LSP issue

**Comment by alexroan** [comment]
Closing due to staleness. Feel free to reopen when this is worked on.
