### ISSUE TITLE
"error: unexpected argument '--ast' found" displayed even when successfully running detectors

### ISSUE THREAD

**Issue by vendrell46** [Cyfrin/aderyn#200]
### Description
I've just used run `aderyn .` in the current contest I'm participating and while it did successfully run detectors and create the `report.md` it seems to display an error even though I didn't pass that argument

### Steps to reproduce
1. Installed aderyn with cargo
2. went to project
3. run `aderyn .`

### Expected result
No errors

### Actual result
```
aderyn .
Detecting framework...
Framework detected: Foundry mode engaged.
Foundry root path: "."
error: unexpected argument '--ast' found

Usage: forge build [OPTIONS]

For more information, try '--help'.
Foundry src path: "./contracts"
Get Detectors
Running 18 detectors
Detectors run, processing found issues
Found issues processed. Printing report
Report printed to report.md
```

**Comment by alexroan** [comment]
This is related to the latest foundry update removing ast files by default.

Please run `foundryup` and try again.

**Comment by vendrell46** [comment]
That worked! Thanks, no more errors are shown.

**Comment by vendrell46** [comment]
Closing the issue as error is no longer displayed
