### ISSUE TITLE
Docker support 

### ISSUE THREAD

**Issue by lukapodlesnik** [Cyfrin/aderyn#208]
I added Docker support for Aderyn so you can run it locally inside the Docker container without the need to install anything (except Docker). If this is something that would be helpful to others I am happy to open a pull request.

**Comment by alexroan** [comment]
That would be epic @lukapodlesnik !

Please do :)

**Comment by TilakMaddy** [comment]
Interesting ... so we can have aderyn run through a given project without having cargo/rust or even foundry/hardhat installed I'm guessing... something like

`docker run -v $project-root:/data <image name>` 

Am I correct 😉 @lukapodlesnik  ?

**Comment by lukapodlesnik** [comment]
Yes correct

**Comment by lukapodlesnik** [comment]
@alexroan I don't think I have the correct permissions to create a new branch and pull request.

**Comment by TilakMaddy** [comment]
It's okay @lukapodlesnik, try to fork the project and then send a PR to the `dev` branch : )

You can watch this video for help : )
https://www.youtube.com/watch?v=a_FLqX3vGR4

**Comment by lukapodlesnik** [comment]
@TilakMaddy thank you. It seems my brain is still running on vacation mode :D
PR opened.

**Comment by lukapodlesnik** [comment]
If this is merged it would be great to add this docker image to Cyfrin's docker Hub so that `docker build` step can be skipped.

**Comment by alexroan** [comment]
Hey @lukapodlesnik ! I can't find the open PR in the PRs tab. Can you try again, please?

**Comment by alexroan** [comment]
Ah, I've just found it and read through the conversation! https://github.com/Cyfrin/aderyn/pull/224

I'll await modifications :)

**Comment by lukapodlesnik** [comment]
New PR opened. Fixed previous issues and made it easier to use.
