### ISSUE TITLE
`forge build --ast` recompiles all contracts when `aderyn` is run

### ISSUE THREAD

**Issue by alexroan** [Cyfrin/aderyn#238]
The old behaviour was that forge would detect when no files were changed, so would not compile again. However, I'm noticing locally that all sol files are recompiled with each run now.

Are you seeing this @TilakMaddy ?

**Comment by alexroan** [comment]
This has seemingly resolved itself

**Comment by TilakMaddy** [comment]
Yes I am noticing the same thing. I think I know why - when you checked out `deetctor/empty-blocks` the existing `cache/solidity-files-cache.json` but new `out/*.json` files
