### ISSUE TITLE
Add Aderyn to brew

### ISSUE THREAD

**Issue by RensR** [Cyfrin/aderyn#267]
Brew is a widely used tool to manage and update dependencies. Having a simple brew command would make adoption even easier.

**Comment by TilakMaddy** [comment]
Creation of CPU native binaries has been integrated only recently in CI/CD  : ) 

We will look into distribution channels : )

Thanks!

**Comment by alexroan** [comment]
@RensR we're almost finished up with `cyfrinup` to install and update aderyn.

Would brew still be preferable in this case?

**Comment by RensR** [comment]
I would still prefer brew but this works as well. Much lower prio with a good installer

**Comment by alexroan** [comment]
Closing to focus on cyfrinup. May revisit later.
