### ISSUE TITLE
Foundry global configuration is not respected

### ISSUE THREAD

**Issue by TilakMaddy** [Cyfrin/aderyn#271]
Sometimes users keep a  `foundry.toml` is in `~/.foundy` which should be respected

**Comment by TilakMaddy** [comment]
Prereq https://github.com/Cyfrin/aderyn/pull/270

**Comment by TilakMaddy** [comment]
Should we though ? Because we rely on `foundry.toml` to be present in the project root to detect the framework. Not sure upsides are big enough for supporting global config where `foundry.toml` lies in the `~/.foundry/`

**Comment by alexroan** [comment]
I think long term, we won't rely/support any specific development framework, we shouldn't go down this path
