### ISSUE TITLE
Renaming thread

### ISSUE THREAD

**Issue by alexroan** [Cyfrin/aderyn#287]
* `sort_by_line_no` -> `sort_by_src_position`?

## Other than `.parent`, we should use the term "ancestor".

* `get_parent_chain` -> `get_ancestral_line`? `get_ancestors`?
* `closest_parent_of_type` -> `closest_ancestor_of_type`?

**Comment by TilakMaddy** [comment]
So we want to rename methods on the node, not the function in the workspace context. Correct? 

Because `parent_chain` is what we have on the node, not `get_parent_chain`

**Comment by alexroan** [comment]
Merged and released
