### ISSUE TITLE
Confusing `ERC20::_mint` for `ERC721`

### ISSUE THREAD

**Issue by imollov** [Cyfrin/aderyn#296]
Reporting `Using ERC721::_mint() can be dangerous` on a `ERC20Upgradeable` based contract.

aderyn 0.0.19

**Comment by alexroan** [comment]
Hey @imollov , how are you calling ERC20 `_mint` in this case?

If it's inheriting the `ERC20Upgradeable` and calling `_mint` from within the contract like this:

```solidity

contract MyContract is ERC20Upgradeable {
  ...
  function foobar() public {
    _mint(...);
  }
  ...
}
```

then this is fixed in #304 :)
