### ISSUE TITLE
High Detector: Checks-effects-interactions

### ISSUE THREAD

**Issue by alexroan** [Cyfrin/aderyn#313]
Ensure that for any function that changes state, if it can be accessed publically or externally, it should exhibit the [Checks-effects-interations](https://docs.soliditylang.org/en/v0.6.11/security-considerations.html#use-the-checks-effects-interactions-pattern) pattern.

If it doesn't, capture the function.

**Comment by malawadd** [comment]
can you please provide a mock contract i can test this against ?
