### ISSUE TITLE
Low Detector: Missing Event

### ISSUE THREAD

**Issue by alexroan** [Cyfrin/aderyn#318]
If a function changes state, but an event is not emitted, capture the function.

**Comment by kree-dotcom** [comment]
Would I be able to be assigned this issue?

**Comment by alexroan** [comment]
> Would I be able to be assigned this issue?

Done @kree-dotcom ! :)

Please tag me here or on a PR if you need help.

**Comment by TilakMaddy** [comment]
Fixed in #714

**Comment by TilakMaddy** [comment]
Fixed in #714
