### ISSUE TITLE
Low Detector: Use `<` instead of `<=`

### ISSUE THREAD

**Issue by alexroan** [Cyfrin/aderyn#319]
Use specific operators instead of "or equal to" operators. If unspecific operators are used, capture them.

**Comment by TilakMaddy** [comment]
Doubt - So if I have `if(a <= b)` I must turn it to `if(!(a > b))` . Is that right?

**Comment by alexroan** [comment]
Deprioritizing this. I don't believe the detector adds value to the developer. Please comment and reopen if yu disagree.
