### ISSUE TITLE
High detector: weak randomness 

### ISSUE THREAD

**Issue by TilakMaddy** [Cyfrin/aderyn#326]
The `keccak256` hash of a combination of predictable values like `block.timestamp`, `block.number`, or any values, should not be accepted as random. Relying on it could harm the protocol. Rather we should use something like Chainlink VRF which gives access to mathematically proven random values on chain.

**Comment by alexroan** [comment]
I think this should be high!

**Comment by DavidDrob** [comment]
Hey, could you assign me this issue?

My plan would be to check for
1. usage of `prevrandao`
2. modulo operations on `block.timestamp` or `block.numer`
3. hashing `block.timestamp` or `block.numer`

**Comment by alexroan** [comment]
> Hey, could you assign me this issue?
> 
> My plan would be to check for
> 
> 1. usage of `prevrandao`
> 2. modulo operations on `block.timestamp` or `block.numer`
> 3. hashing `block.timestamp` or `block.numer`

Done @DavidDrob ! :)
