### ISSUE TITLE
Having trouble running this on my linux mint machine

### ISSUE THREAD

**Issue by Caullyn** [Cyfrin/aderyn#345]
**Describe the bug**
I followed the README instructions. The cargo install works, but I can't get the command aderyn to run, or the docker image commands.

**To Reproduce**
1. Cargo install (todo bien)
2. here's my terminal commands pasted:
 ll@ll-IdeaPad-3-15ADA05:~/repos/aderyn$ sudo docker login
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username: colin.sloss@gmail.com
Password: 
WARNING! Your password will be stored unencrypted in /root/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
sudo docker run -v .:/share aderyn
Unable to find image 'aderyn:latest' locally
docker: Error response from daemon: pull access denied for aderyn, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
ll@ll-IdeaPad-3-15ADA05:~/repos/aderyn$ aderyn .
aderyn: command not found

**Expected behavior**
I thought I could run aderyn on some smart contracts I want to audit, but not quite there.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ll@ll-IdeaPad-3-15ADA05:~/Downloads$ lsb_release -a
No LSB modules are available.
Distributor ID:	Linuxmint
Description:	Linux Mint 21.2
Release:	21.2
Codename:	victoria

 - Browser: Chrome
 - Version  122.0.6261.94 (Official Build) (64-bit)

**Comment by Equious** [comment]
Resolved in Discord  https://discord.com/channels/1127263608246636635/1226257559669837896/1230487785002110976
