### ISSUE TITLE
Add External call "attack surface" to the contract

### ISSUE THREAD

**Issue by PatrickAlphaC** [Cyfrin/aderyn#349]
**Is your feature request related to a problem? Please describe.**
Let's say I have the following contract:

```javascript
contract MyContract {
  address hardCoded = address(1);

  function callOutSpecific() external {
    hardCoded.call("");
  }

  function callOutAny(address myAddress) external {
    myAddress.call("");
  }
}
```

I'd like aderyn to:
1. Give us a list of addresses that the contract calls out to
2. What functions can make those calls out

For example, the above contract returns:
- hardCoded: callOutSpecific
- HAVOC: callOutAny

Where `HAVOC` means "any address" 

cc @zobront

**Comment by zobront** [comment]
Love this, thank you @PatrickAlphaC .

I imagine it might be cleaner to organize by the actual CALL op codes in the code. I can imagine a table something like `forge inspect <contract> methods --pretty` that would look like:

| call location (which function?) | call (code) | where is called address from? |
| ------ | ----- | ----- | 
| `callOutAny()` | `myAddress.call("");` | havoc | 
| `callOutSpecific()` | `hardCoded.call("");` | storage |

**Comment by PatrickAlphaC** [comment]
more context:

It could be an optional flag:

```bash
aderyn --attack-surface
```

**Comment by TilakMaddy** [comment]
Ahh for this one, if we want to use `aderyn` we must do the following: 

1) Search for MemberAccess with function name `call`
2) Filter out those where the object of the member access has TypeName address
3) Then for each of those, capture `closest_ancestor_of_type(context, NodeType::FunctionDefinition)`

Try it out and let me know : )

**Comment by TilakMaddy** [comment]
Oh wait ...I think got it now. You are asking this as a feature from aderyn; not a detector.

**Comment by alexroan** [comment]
@PatrickAlphaC @zobront What is the range of external call methods that you would like included in this? Raw calls (and delegatecalls) only? Or specific function calls on contracts/interfaces with variable addresses also?

What would be most helpful?

**Comment by zobront** [comment]
@alexroan All of them!

**Comment by alexroan** [comment]
The latest release adds "Auditor Mode". This is an experimental mode intended to provide useful helpers for auditors.
The first helper added is this attack surface helper! Try it out by running `aderyn --auditor-mode` on a foundry repo.

Here's an example of the CLI output, when run on [this repo](https://github.com/Cyfrin/aderyn-contracts-playground):

```
+---------------------+-----------------------------------------+--------------------------------------+----------------+
| Contract            | Function                                | Code                                 | Address Source |
+---------------------+-----------------------------------------+--------------------------------------+----------------+
| ExternalCalls       | rawCallFromStorage                      | target.call                          | Storage        |
| ExternalCalls       | rawCallFromParameter                    | myTarget.call                        | Havoc          |
| ExternalCalls       | rawDelegateCallFromStorage              | target.delegatecall                  | Storage        |
| ExternalCalls       | rawDelegateCallFromParameter            | myTarget.delegatecall                | Havoc          |
| ExternalCalls       | rawCallToInterfaceFromStorage           | address(targetContract).call         | Storage        |
| ExternalCalls       | rawCallToInterfaceFromParameter         | address(myTarget).call               | Havoc          |
| ExternalCalls       | rawDelegateCallToInterfaceFromStorage   | address(targetContract).delegatecall | Storage        |
| ExternalCalls       | rawDelegateCallToInterfaceFromParameter | address(myTarget).delegatecall       | Havoc          |
| ExtendedInheritance | doSomethingElse                         | target.delegatecall                  | Havoc          |
+---------------------+-----------------------------------------+--------------------------------------+----------------+
```

cc: @zobront @PatrickAlphaC

**Comment by zobront** [comment]
Amazing. Thanks @alexroan — looking forward to trying it.
