### ISSUE TITLE
Low detector: Solidity style guide - Order of layout

### ISSUE THREAD

**Issue by TilakMaddy** [Cyfrin/aderyn#354]
Implement a detector that captures contracts where order of layout for events, functions, state variables, modifiers, etc is not followed

Ref: https://docs.soliditylang.org/en/latest/style-guide.html#order-of-layout

Hint: Use the trait `SortNodeReferencesToSequence` which gives you access to the method `sort_by_src_position()` which can be called on a vector of `ASTNode`s

**Comment by alexroan** [comment]
I'm concerned that this is a Style Guide and not a security issue. For the purposes of the hackathon, we will consider PRs, but in general I'm not sure it fits within Aderyn's remit.

**Comment by alexroan** [comment]
Closing this due to the above reason, but I will judge the submissions as if they were valid (#385 )
