### ISSUE TITLE
Use collapsible sections on the report.md 

### ISSUE THREAD

**Issue by devtooligan** [Cyfrin/aderyn#447]
Hey team, I just ran installed and ran Aderyn for my first time.  Amazingly simple to get it going!!  I will be diving in more soon.  Here is an idea I thought of.

**Is your feature request related to a problem? Please describe.**

The problem is the report can be a little difficult to navigate especially when there's dozens of instances of a particular finding.

**Describe the solution you'd like**

Show the first 3 or so and then use a collabsible section to show the rest.  Something like this:

```
- Found in contracts/test/helpers/XXXXXXX.sol [Line: 22](contracts/test/helpers/XXXXXXX.sol#L22)

	```solidity
	                    abi.encodePacked(reason, "\nInsufficient ", IERC20Metadata(token).symbol(), " balance on account: ")
	```

- Found in contracts/test/helpers/XXXXXXX.sol [Line: 37](contracts/test/helpers/XXXXXXX.sol#L37)

	```solidity
	                    abi.encodePacked(reason, "\nExceeding ", IERC20Metadata(token).symbol(), " balance on account: ")
	```

- Found in contracts/test/helpers/XXXXXXX.sol [Line: 52](contracts/test/helpers/XXXXXXX.sol#L52)

	```solidity
	                    abi.encodePacked(reason, "\nIncorrect ", IERC20Metadata(token).symbol(), " balance on account: ")
	```

<details>
  <summary>29 additional findings </summary>

- Found in contracts/test/helpers/XXXXXXX.sol [Line: 52](contracts/test/helpers/XXXXXXX.sol#L52)

	```solidity
	                    abi.encodePacked(reason, "\nIncorrect ", IERC20Metadata(token).symbol(), " balance on account: ")
	```

- Found in contracts/test/helpers/XXXXXXX.sol [Line: 68](contracts/test/helpers/XXXXXXX.sol#L68)

	```solidity
	            emit log_named_address(string(abi.encodePacked(reason, "Incorrect ETH balance on account: ")), account);
	```

	etc
</details>

```

**Comment by alexroan** [comment]
Great idea. Do you think wrapping the whole set of finding locations within a collapsible section be cleaner?

**Comment by alexroan** [comment]
Thoughts on [this](https://github.com/Cyfrin/aderyn/blob/7f8936604e8b6fbbd728a925849e597461b9cecd/reports/report.md) @devtooligan ?

**Comment by devtooligan** [comment]
> this


That looks AMAZING!!

I think anyway you can improve the navigation of the report will be an improvement.  

I didn't want to spam you with ideas but I was also thinking of some sort of anchors that you click on maybe in the title of the finding that would take you back to the TOC but not sure about that one because I think most people could just hit their home key to go to the top, so maybe not needed. (Me personally, I havent figure out how to go to Home on my VSCode yet 🤦)

I wonder also if you could do even more with collapsible sections.  Like wrap entire findings and just show the name, and then wrap entire severity categories (like High).  In both cases you could have the section default to open which I just learned you can do by applying the open attr to the details tag, `<details open>`.  You could leave them open by default but people could close them as they reviewed them or to make it easier to navigate the report or something...

Anyways, yeah, report UX should be given extra thought imo, especially because some of these codebases are so dang large.
