### ISSUE TITLE
Follow ups from Removing Legacy Workflow

### ISSUE THREAD

**Issue by alexroan** [Cyfrin/aderyn#491]
Looks good to me!

I'm going to request only a few changes. (But they are not objectively wrong. just dropping them here in case you have missed them)

1. Here, IMO the `src` values passed as a command line argument must replace the config value 
https://github.com/Cyfrin/aderyn/blob/d7484b0b1210fd026a225ca7b174a19efdd92d3b/aderyn_driver/src/config_helpers.rs#L72

2. I think it would make more sense to move the logic to obtain remappings from [here](https://github.com/Cyfrin/aderyn/blob/d7484b0b1210fd026a225ca7b174a19efdd92d3b/aderyn_driver/src/process_auto.rs#L41) to [here](https://github.com/Cyfrin/aderyn/blob/d7484b0b1210fd026a225ca7b174a19efdd92d3b/aderyn_driver/src/driver.rs#L155)

3. Can you also remove foundry-toolchain installation in CI and verify that it works?

UPDATE:
In the previous edit of this, I said something was unreachable and replaceable. That's not true. My bad : )

_Originally posted by @TilakMaddy in https://github.com/Cyfrin/aderyn/issues/488#issuecomment-2141700560_

**Comment by TilakMaddy** [comment]
Hmm ... Is `forge build` command really needed though in CI? It's also taking up too much time. 
Running `make` in CI might be an overkill IMO but not sure if there's a way arounf
