### ISSUE TITLE
AST Error - SourceUnit lacks top level `FunctionDefinition` hence `ErrorDefinition` falsely deserializes objects

### ISSUE THREAD

**Issue by TilakMaddy** [Cyfrin/aderyn#500]
Functions defined freely outside of contracts in a helper file are read as `ErrorDefinition` instead  `FunctionDefinition` 

Problems:

1) It's a semantic error (this is bad enough)
2) The function's body doesn't make it into the AST (because ErrorDefinitions don't have bodies)

BTW, it deserializing fails silently like this. You won't see any panics

**Comment by alexroan** [comment]
Can you show an example of this @TilakMaddy ?

**Comment by TilakMaddy** [comment]
@alexroan 

You can try this

```
git clone https://github.com/transmissions11/solmate
forge build
aderyn
```

**Comment by TilakMaddy** [comment]
@alexroan  

UPDATE:

I think I just fixed it :) 😉 
Will send a PR
