### ISSUE TITLE
Missing checks for `address(0)` needs tuning

### ISSUE THREAD

**Issue by devtooligan** [Cyfrin/aderyn#517]
**Detector Title**
Missing checks for `address(0)` when assigning values to address state variables

**Repository details**
Got these hits:

## L-3: Missing checks for `address(0)` when assigning values to address state variables
Check for `address(0)` when assigning values to address state variables.

<details><summary>5 Found Instances</summary>

- Found in vulnerable.sol [Line: 34](vulnerable.sol#L34)

	```solidity
	            balances[msg.sender] -= _amount;
	```

- Found in vulnerable.sol [Line: 125](vulnerable.sol#L125)

	```solidity
	        balanceOf[msg.sender] -= _value;
	```

- Found in vulnerable.sol [Line: 126](vulnerable.sol#L126)

	```solidity
	        balanceOf[_to] += _value;
	```

- Found in vulnerable.sol [Line: 141](vulnerable.sol#L141)

	```solidity
	        currentRecipient = _recipient;
	```

- Found in vulnerable.sol [Line: 197](vulnerable.sol#L197)

	```solidity
	        owner = address(newOwner);
	```

</details>

**Expected behavior**
Detector should check if the state var being updated is an address type, it appears it is just checking if an address is involved in the operation at all (in this case it is a key to a mapping)

**Comment by alexroan** [comment]
This fix will be available in the upcoming #560 release
