### ISSUE TITLE
Enable single Solidity files to be parsed

### ISSUE THREAD

**Issue by alexroan** [Cyfrin/aderyn#53]

**Comment by TilakMaddy** [comment]
Hey @alexroan I have attempted to do this in my new PR. Any comments highly appreciated.

BTW

Would you also like to have python bindings? 

it will look something like this - 

```python

import aderyn

def generate_report():
    aderyn.generate_report_for("path/to/filename.sol", "output/report.md")

```

and then python users need not install any rust stuff like cargo, etc... They can just do pip install aderyn.
I feel like this way more people will use it.

**Comment by alexroan** [comment]
@TilakMaddy Absolutely! Python bindings would be sick!
