### ISSUE TITLE
Something doesn't feel right with the speed of execution of aderyn release binaries

### ISSUE THREAD

**Issue by TilakMaddy** [Cyfrin/aderyn#557]
Let me explain 

Choose a large repo like lssvm2.

**First try**

Run `cargo build --verbose --locked --release --package aderyn --target x86_64-apple-darwin` locally
Then run `./target/x86_64-apple-darwin/release/aderyn path/to/lssvm2 -o option1.md`

(Measure the time)

**Second try**

Do the whole `cyfrinup` thing to get the Aderyn binary (or manually download it and unzip it from releases)
Then run `aderyn path/to/lssvm2 -o option2.md`

(Measure the time)

### I find that the First try takes **significantly** less time in resolving sources by graph step and is almost instantaneous whereas the second try seems to behave more like the dev version where it is taking a few seconds in the graph resolution step

@alexroan Please 🙏 can you try this experiment too ?

**Comment by alexroan** [comment]
I ran this:

`cargo build --verbose --locked --release --package aderyn`
`./target/release/aderyn path/to/lssvm2`

and

`cargo build --locked --release --package aderyn --target aarch64-apple-darwin
`./target/aarch64-apple-darwin/release/aderyn /path/to/lssvm2/`

And this was very similar speed to `cyfrinup && aderyn`.

Could you dig into how your release binary is being built differently to the x86_64 darwin build in CI please @TilakMaddy ? We might be missing something.

**Comment by alexroan** [comment]
Fixed, will be released in v0.1.4

**Comment by TilakMaddy** [comment]
Finally !!! Now I'm able to run the latest fastest aderyn with cyfrinup on my mac.  Can't wait for nightly builds <3
