### ISSUE TITLE
Wrongly assigned values to sarif report

### ISSUE THREAD

**Issue by TilakMaddy** [Cyfrin/aderyn#558]
https://github.com/Cyfrin/aderyn/blob/96b423789ef36ae970d6ba975165a5daa2fcef5c/aderyn_core/src/report/sarif_printer.rs#L224-L228

The values `Some(offset.parse().unwrap())` and `Some(len.parse().unwrap())` are byte offset and byte length respectively

**Comment by alexroan** [comment]
This fix will be released in v0.1.4
