### ISSUE TITLE
Error Detecting Framework

### ISSUE THREAD

**Issue by alfheimrShiven** [Cyfrin/aderyn#57]
I installed Rust on my system and tried to use Aderyn on my solidity projects. On running `aderyn .` in my VSCode terminal of the project directory, I get the error 
```zsh
shiven@Shivendras-MacBook-Pro vulnerability-detection-exercises % aderyn .
Detecting framework...
Error detecting framework
```

I even tried running Aderyn after mentioning the full path to the project directory, but no luck!

**Comment by alexroan** [comment]
Can you give some more details about the repo please?

**Comment by alfheimrShiven** [comment]
Hey @alexroan, here it is: https://github.com/alfheimrShiven/vulnerability-detection-exercises

**Comment by alfheimrShiven** [comment]
@alexroan this is fixed now. I had the project structure of a Remix project. I modified it to local Foundry project and now aderyn is detecting the framework. Closing this. Thanks!
