### ISSUE TITLE
Feat: provide support for python

### ISSUE THREAD

**Issue by programskillforverification** [Cyfrin/aderyn#628]
**Is your feature request related to a problem? Please describe.**
Aderyn can be import as python module now. For a python user, it's better to use all `Args` options as python function's dynamic number of arguments, like
`generate_report(root, output, **kwargs)`

**Describe the solution you'd like**
First, update the `py03` version, which can compatible with python3.12 and provide more clean `pymodule` definition. Then, use `PyDict` or `PyTuple` to rewrite this rust function.

**Additional context**

**Comment by programskillforverification** [comment]
I would like to add this feature, please assign to me

**Comment by TilakMaddy** [comment]
Thanks for showing interest! 

Yes, python bindings were on a backburner for a while now. It would be great to see you complete it with richer definitions in pymodule. 

Go for it @programskillforverification  :)
