### ISSUE TITLE
Formal release process (CI/CD?)

### ISSUE THREAD

**Issue by alexroan** [Cyfrin/aderyn#69]
Publishing versions of:
- crates
- python bindings
- node bindings

**Comment by alexroan** [comment]
Hey @TilakMaddy , I've read through the doc. Most makes sense.

What would be the best next steps here? My instinct is to focus on Python bindings first: Create bash scripts that can be used to publish the bindings, and test those out.

**Comment by TilakMaddy** [comment]
Yes Alex...I will address your questions shortly

**Comment by lukapodlesnik** [comment]
@alexroan  you should add a docker image to the list. When an ew version is released CI/CD automatically builds the container image from GitHub and push it Docker Hub.
If you are planing to use Github actions this would be the flow: https://docs.github.com/en/actions/publishing-packages/publishing-docker-images

**Comment by alexroan** [comment]
I'm restricting the scope of this to formal CI releases, which is captured in #514
