### ISSUE TITLE
Missing Contracts during Scan not falling in path-exclude pattern

### ISSUE THREAD

**Issue by ds-rgangavasi** [Cyfrin/aderyn#697]
**Missing Contracts during Scan not falling in path-exclude pattern**
In Repo: https://github.com/AladdinDAO/aladdin-v3-contracts
- It has 416 solidity files, while aderyn only scans 221 solidity files
**- aderyn skips 195 solidity files**
- command used: aderyn . --output autogen_output/output.json --path-excludes \.t\.sol,\.s\.sol,tests/,lib/,node_modules/
- issue is that these 195 solidity files doesn't falls in path-excludes pattern, those 195 files are listed here: [https://docs.google.com/spreadsheets/d/1Xsy-8racaGU_rDla88MVCx9fhvIFTwj8EnhBPdn4MTw/](https://docs.google.com/spreadsheets/d/1Xsy-8racaGU_rDla88MVCx9fhvIFTwj8EnhBPdn4MTw/?authuser=0)

**To Reproduce**
1. Clone repo: https://github.com/AladdinDAO/aladdin-v3-contracts
2. Run aderyn with this: aderyn . --output autogen_output/output.json --path-excludes \.t\.sol,\.s\.sol,tests/,lib/,node_modules/
3. See error: Scanned only 221 solidity files

**Expected behavior**
Expecting it to check rest of the files that do not fall in path-excludes pattern

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.3 LTS 
 - Architecture: x86-64
 - Aderyn Version: 0.1.11

**Comment by TilakMaddy** [comment]
Create a `remappings.txt` with this data
```
@openzeppelin/=node_modules/@openzeppelin/
@uniswap/=node_modules/@uniswap/
```

Then run `aderyn -s contracts/`

That scans 424 files :)
