### ISSUE TITLE
Stack too deep when compiling inline assembly

### ISSUE THREAD

**Issue by ds-rgangavasi** [Cyfrin/aderyn#698]
**Stack too deep when compiling inline assembly**
In Repo: https://github.com/smartcontractkit/ccip
  - It has 582 solidity files, quite a large project
  - when checking with aderyn it provides following error: 
```
"stderr = Compiler error: Stack too deep when compiling inline assembly: Variable headStart is 1 slot(s) too deep inside the stack.

cwd = ccip/contracts
Error running solc command ^^^

thread '<unnamed>' panicked at /home/runner/work/aderyn/aderyn/aderyn_core/src/lib.rs:166:26:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at /home/runner/work/aderyn/aderyn/aderyn_core/src/lib.rs:166:26:
called `Option::unwrap()` on a `None` value
thread '<unnamed>' panicked at /home/runner/work/aderyn/aderyn/aderyn_core/src/lib.rs:166:26:
called `Option::unwrap()` on a `None` value
thread '<unnamed>' panicked at /home/runner/work/aderyn/aderyn/aderyn_core/src/lib.rs:166:26:
called `Option::unwrap()` on a `None` value
thread '<unnamed>thread '<unnamed>' panicked at /home/runner/work/aderyn/aderyn/aderyn_core/src/lib.rs:166:26:
called `Option::unwrap()` on a `None` value
' panicked at /home/runner/work/aderyn/aderyn/aderyn_core/src/lib.rs:166:26:" 
```
- wanted to confirm if aderyn has some limitations on length, where can I read more about it.

**To Reproduce**
1. Clone repo:  https://github.com/smartcontractkit/ccip
2. Run aderyn with this: aderyn . --output autogen_output/output.json --path-excludes \.t\.sol,\.s\.sol,tests/,lib/,node_modules/
3. See error: 
```
"stderr = Compiler error: Stack too deep when compiling inline assembly: Variable headStart is 1 slot(s) too deep inside the stack.

cwd = ccip/contracts
Error running solc command ^^^

thread '<unnamed>' panicked at /home/runner/work/aderyn/aderyn/aderyn_core/src/lib.rs:166:26:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at /home/runner/work/aderyn/aderyn/aderyn_core/src/lib.rs:166:26:
called `Option::unwrap()` on a `None` value
thread '<unnamed>' panicked at /home/runner/work/aderyn/aderyn/aderyn_core/src/lib.rs:166:26:
called `Option::unwrap()` on a `None` value
thread '<unnamed>' panicked at /home/runner/work/aderyn/aderyn/aderyn_core/src/lib.rs:166:26:
called `Option::unwrap()` on a `None` value
thread '<unnamed>thread '<unnamed>' panicked at /home/runner/work/aderyn/aderyn/aderyn_core/src/lib.rs:166:26:
called `Option::unwrap()` on a `None` value
' panicked at /home/runner/work/aderyn/aderyn/aderyn_core/src/lib.rs:166:26:" 
```

**Expected behavior**
Expecting Aderyn to scan large and complex projects

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.3 LTS 
 - Architecture: x86-64
 - Aderyn Version: 0.1.11

**Comment by TilakMaddy** [comment]
ccip has different profiles in which they run. (you can look inside foundry.toml)

If you don't set any profile, aderyn would try to sort through *all* the files and that is not the intended behavior anyways :)

Profile here - https://github.com/smartcontractkit/ccip/blob/ccip-develop/contracts/foundry.toml
Choose from `ccip`, `functions`, `vrf`, etc ... 

Then run aderyn. Also make sure to exclude stuff like tests

Example:

> aderyn ccip-contracts/contracts --src src/v0.8/functions/ -x "tests/,test/,mocks/" -o ./reports/ccip-functions-report.md
