### ISSUE TITLE
package referring to another package which is not available in package.json therefore not added in remappings.txt

### ISSUE THREAD

**Issue by ds-rgangavasi** [Cyfrin/aderyn#699]
**package referring to another package which is not available in package.json therefore not added in remappings.txt**
In Repo: https://github.com/sherlock-audit/2024-02-radicalxchange
  - I have automated a process to create remappings.txt from package.json if not already available
  - I copy dependencies and devDependencies from json to txt in required format
  - In this repo, we do not have @openzeppelin/contracts in package.json
  - But package like @superfluid-finance/ethereum-contracts depends on it
  - Since package referring to another package that is not available in package.json therefore not added in remappings.txt, gives following error:
```
Error: Source "@openzeppelin/contracts/token/ERC721/extensions/IERC721Metadata.sol" not found: File not found. Searched the following locations: "".
 --> node_modules/@superfluid-finance/ethereum-contracts/contracts/interfaces/superfluid/IFlowNFTBase.sol:4:1:
  |
4 | import {
  | ^ (Relevant source part starts here and spans across multiple lines).
- solution: add openzeppelin to remappings.txt
@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/
```
  - Adding @openzeppelin/contracts to remappings make it work
  - But in order to automate this process, what should be the right approach to create a remappings.txt automatically
 
**To Reproduce**
1. Clone repo: https://github.com/sherlock-audit/2024-02-radicalxchange
2. Run aderyn with this: aderyn . --output autogen_output/output.json --path-excludes \.t\.sol,\.s\.sol,tests/,lib/,node_modules/
3. See error: 
```
Error: Source "@openzeppelin/contracts/token/ERC721/extensions/IERC721Metadata.sol" not found: File not found. Searched the following locations: "".
 --> node_modules/@superfluid-finance/ethereum-contracts/contracts/interfaces/superfluid/IFlowNFTBase.sol:4:1:
  |
4 | import {
  | ^ (Relevant source part starts here and spans across multiple lines).
- solution: add openzeppelin to remappings.txt
@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/
```

**Expected behavior**
Expecting a document to automate creation of the remappings.txt file 

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.3 LTS 
 - Architecture: x86-64
 - Aderyn Version: 0.1.11

**Comment by TilakMaddy** [comment]
You can use the remappings described here in the `remappings.txt`

https://github.com/sherlock-audit/2024-02-radicalxchange/blob/main/pco-art/echidna-config.yaml

**Comment by TilakMaddy** [comment]
Also I think you can re-use the ones given to slither here

https://github.com/sherlock-audit/2024-02-radicalxchange/blob/main/pco-art/slither.config.json
