### ISSUE TITLE
Requesting clarification 

### ISSUE THREAD

**Issue by TilakMaddy** [Cyfrin/aderyn#70]
So I see this point in medium term goals section in the readme

>  installer that doesn't require Rust (aderynup)

Doubt:

Rust compiles the code to native binary. (there is no runtime). So if people have to use the aderyn cli we can distribute that cli natively for each architecture - (lookup these commands: rustup target add XXXX) and allow download. Done ! No rust in  the picture : )

I feel like `cyfrinup` would make more sense than `aderynup` because then you can make the argument that we need a binary to sit in the user's computer which will be responsible for fetching and downloading other binaries offered by cyfrin such as aderyn, etc, etc ... and keep them up to date.

Even then you wouldn't need Rust !

I may be going wrong somewhere in my thought process. If anybody is kind enough to explain I'll be very grateful

**Comment by alexroan** [comment]
I love how you're thinking about this. I had a similar conversation with @Eversmile12 just yesterday!
