### ISSUE TITLE
contract-locks-ether Should look for `withdraw` functions in the inheritance/extension graph

### ISSUE THREAD

**Issue by alexroan** [Cyfrin/aderyn#742]
**Detector Title**
contract-locks-ether

**To Reproduce**
1. Create a base contract with a withdraw function
2. Create an child contract with a payable function
3. This detector captures the child contract despite a withdraw function being present

**Expected behavior**
Withdraw function should be found in the inheritance graph

**Comment by TilakMaddy** [comment]
when you say create a withdraw function, does it actually mean a function that sends eth away using `address.call{value: xxx}()` / transfer  /send  ?

**Comment by TilakMaddy** [comment]
@alexroan Please checkout the fix in the branch and close the issue if it works
