### ISSUE TITLE
Add support for `aderyn init <optional_path>`

### ISSUE THREAD

**Issue by TilakMaddy** [Cyfrin/aderyn#744]
Currently we can do

* aderyn init

It creates an `aderyn.toml` file in the project root

What we also want

* aderyn init <optional_path>

This should create an `aderyn.toml` file in the optional path provided. (also make sure the optional_path is an existing directory)

_Originally posted by @TilakMaddy in https://github.com/Cyfrin/aderyn/pull/722#discussion_r1766652385_

**Comment by mgiagante** [comment]
@TilakMaddy Is it ok if I take this one? I'd love to start contributing and this seems like a good first issue.

**Comment by TilakMaddy** [comment]
Sure! Thanks for taking interest @mgiagante  :)

**Comment by mgiagante** [comment]
Created https://github.com/Cyfrin/aderyn/pull/762 to address this issue.
