### ISSUE TITLE
Aderyn crashes when update check fails

### ISSUE THREAD

**Issue by aryankaushik11** [Cyfrin/aderyn#751]
A fatal compiler bug occurs when running Aderyn after vulnerabilities are detected. The **report is successfully generated in report.md**, but an error interrupts the process with a "Fatal compiler bug!" message. This didn't happen in the previous versions I used.

**To Reproduce**
This error showed up for all of the smart contracts on which I tried to run the code for.

**Expected behavior**
Expected behavior The report should be generated successfully without a fatal error.

**Screenshots**
![image](https://github.com/user-attachments/assets/d34eaee6-176e-4029-aa84-d0e8c4a6f6e0)

**Desktop (please complete the following information):**
 - OS: WSL 2
 - Aderyn Version: 0.3.0
 - Solc version: 0.8.26

**Comment by Latikesh22** [comment]
### **Issue Description:**

I am running a script to scan smart contracts located in a specified folder sequentially. The initial scans proceed without issue, and I successfully receive the report.md file for each contract. However, after processing approximately 10 to 15 contracts, I encounter a recurring error as noted in the above section.

### **Environment:**

- Aderyn version: 0.3.0
- Operating System: Linux

I would appreciate any insights or suggestions to resolve this issue. Thank you for your assistance.

**Comment by TilakMaddy** [comment]
You can add this flag  `--skip-update-check` and it won't error

**Comment by Latikesh22** [comment]
Thank you for your assistance; the solution is now working. I appreciate your support.
